### ISSUE TITLE
Integrate TravisCI in this project

### ISSUE THREAD

**Issue by aviaryan** [systers/postorius#18]
Right now, we have a dummy (incorrect) `build` badge in README.

> .. image:: https://img.shields.io/travis/rust-lang/rust.svg?style=plastic   :target: https://github.com/systers/postorius

I also see that we have a `.gitlab-ci.yml` file. Since GitlabCI will not work here on GitHub, I guess we should switch to Travis now. In fact, it seems that the project has already been added to Travis, as is evident from [this build](https://travis-ci.org/systers/postorius/builds/343065430?utm_source=github_status&utm_medium=notification). 

But we are missing a `.travis.yml` file. So the goal of this issue is to add a `.travis.yml` to this repository. We can use the `.gitlab-ci.yml` file as the starting point.

**Comment by yashLadha** [comment]
Can i take up this issue @aviaryan .

**Comment by aviaryan** [comment]
Yes, please send a PR. Make sure the build passes in the PR.

**Comment by naman1901** [comment]
If no one is actively working on this, @Monal5031 can take it up as part of his GSoC work.

**Comment by yashLadha** [comment]
Sure GFI @Monal5031

**Comment by Monal5031** [comment]
@naman1901 @pavankm Please update this issue description to remove gitlab-ci.yml too.
